# Generated by Django 2.0.2 on 2018-03-30 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaybooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('discussion', models.TextField(help_text='Enter your comments here', max_length=2000)),
                ('approved', models.BooleanField(default=False)),
                ('datecreated', models.DateField(default=datetime.datetime(2018, 3, 30, 11, 33, 38, 976594))),
                ('dateapproved', models.DateField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publishdate']},
        ),
    ]
