# Generated by Django 2.0.2 on 2018-03-30 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaybooks', '0002_auto_20180330_1133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-datecreated']},
        ),
        migrations.AddField(
            model_name='discussion',
            name='subject',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discussion',
            name='datecreated',
            field=models.DateField(default=datetime.datetime(2018, 3, 30, 14, 15, 32, 728639)),
        ),
    ]
