# Generated by Django 2.0.2 on 2018-03-30 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displaybooks', '0003_auto_20180330_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='datecreated',
            field=models.DateField(default=datetime.datetime(2018, 3, 30, 14, 18, 4, 562921)),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
    ]
